### ISSUE TITLE
[bug?] MONGOKU_DEFAULT_HOST - Not able to set it correctly

### ISSUE THREAD

**Issue by avico78** [huggingface/Mongoku#59]
when configuring the Mongo DB via MogoKU GUI by clicking on "Add server".
using "admin:admin@mongo_db:27017" connection string and it's working.

but it doesn't work using the variable MONGOKU_DEFAULT_HOST in docker-compose .

docker-compose:
```
  mongo_gui:
    image: huggingface/mongoku
    container_name: mongo_gui
    ports:
      - "${MONGOGUI_PORT:-3100}:3100"
    networks:
      - dockers_default
    depends_on:
        - mongo_db
    environment:
      - MONGOKU_DEFAULT_HOST="mongodb://admin:admin@mongo_db:27017"

```
Tried also:
MONGOKU_DEFAULT_HOST="mongo_db://admin:admin@mongo_db:27017"
MONGOKU_DEFAULT_HOST="mongodb://admin:admin@localhost:27017"
MONGOKU_DEFAULT_HOST="admin:admin@mongo_db:27017"

I doesn't connect and there's an error "unescaped slash in user info section "
